# This is a basic workflow to help you get started with Actions
name: checkout_test_wf

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout my python docker repo
        uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout my python docker repo
        uses: actions/checkout@v2
        with:
          repository: Virajdatt/Python_Docker
          ref: master
          path: ./Python_docker
      - name: List what was checked out
        run: ls -ltr
      

      # Runs a single command using the runners shell
      - name: Run a multi-line script on Ubuntu
        run: |
          ls
          cat README.md
